# Generated by Django 6.0.3 on 2026-03-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Admin Profile', 'verbose_name_plural': 'Admin Profiles'},
        ),
    ]
