# Generated by GitHub Copilot on 2026-03-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_miscellaneous'),
        ('Communication', '0006_directmessagethread_chatmessage_chatreaction_and_more'),
        ('authentication', '0007_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('user_joins', 'User Joins'), ('new_message', 'New Message')], max_length=50)),
                ('action_type', models.CharField(choices=[('send_message', 'Send Message'), ('send_email', 'Send Email')], max_length=50)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to='authentication.user')),
                ('workspace', models.ForeignKey(blank=True, help_text='If set, automation only applies to this workspace. Otherwise applies to all workspaces.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='Communication.workspace')),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='Admin.automation')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='Communication.channel')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='Communication.chatmessage')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='authentication.user')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='Communication.workspace')),
            ],
            options={
                'verbose_name': 'Automation Execution',
                'verbose_name_plural': 'Automation Executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
