# Generated by Django 6.0.3 on 2026-03-25 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Communication', '0007_chatattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=128, unique=True)),
                ('context_type', models.CharField(choices=[('workspace', 'Workspace'), ('channel', 'Channel'), ('dm', 'Direct Message')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_video', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='Communication.channel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calls', to=settings.AUTH_USER_MODEL)),
                ('dm_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='Communication.directmessagethread')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='Communication.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Calls.call')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_call_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['context_type', 'is_active'], name='Calls_call_context_008656_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['started_at'], name='Calls_call_started_0a52ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='callparticipant',
            constraint=models.UniqueConstraint(fields=('call', 'user'), name='unique_call_participant'),
        ),
    ]
