# Generated by Django 6.0.3 on 2026-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0002_channel_user_workspace_user_alter_workspace_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='sharable_link',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='sharable_link',
        ),
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
