# Generated by Django 6.0.3 on 2026-03-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0003_remove_channel_sharable_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
