# Generated by Django 6.0.3 on 2026-05-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0007_chatattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
